const registry = [
"BINGO",
"Baby Shark (Challenge Version)",
"Broadway, broadway, broadway",
"Candy",
"Defiying Gravity",
"Five Little Monkeys",
"Hope Your Ok",
"Hopelessly Devoted",
"I Love You",
"Learn Piano With Sesamie Theme",
"Maria",
"Michael With A Creeper",
"Michael With a Creeper [Radio Edit]",
"Mister Mistophiles",
"Oh Where Oh Where Has My Little Dog Gone",
"Screw Loose [Radio Edit]",
"Screw Loose",
"That's Paradise EN",
"That's Paradise JP-RO",
"That's Paradise JP",
"Twinkle Twinkle Little Star ABCs",
"Walfing through the window",
"Wheels on the Bus",
];
